### ISSUE TITLE
No styling change when widget is disabled

### ISSUE THREAD

**Issue by mwcraig** [jupyter-widgets/ipywidgets#1431]
Prior to ipywidgets 6, when a widget was disabled its style was changed so that it looked faded, as shown in the pic below. Starting with ipywidgets 6 when `disabled=True` the widget is disabled but the style does not change.

![button-disable](https://user-images.githubusercontent.com/1147167/27297874-38396694-54ec-11e7-85b7-e82ac735d05f.gif)

**Comment by jasongrout** [comment]
Can you see what happens to the styling in that case in 5.0 (i.e., inspect it in the debugger and see how the styling changes and where the change comes from)? I think maybe that shading or opacity came from the bootstrap styles. I don't see in our code in the 5.x branch where we explicitly changed the styling.

**Comment by mwcraig** [comment]
Will try, but I'm inexperienced at best with the javascript debugger...

**Comment by mwcraig** [comment]
If I'm reading the developer tools in chrome correctly, when disabled is set to True that simply adds a `disabled` tag to the button. That in turn changes what css is applied. In `buttons.less` (from bootstrap) this is picked up a selector that fades the button:

```css
.btn.disabled, .btn[disabled], fieldset[disabled] .btn {
    cursor: not-allowed;
    opacity: 0.65;
    filter: alpha(opacity=65);
    -webkit-box-shadow: none;
    box-shadow: none;
}
```
