### ISSUE TITLE
Setting appropriate colors for dark theme seems not to be possible

### ISSUE THREAD

**Issue by kramerfelix** [jupyter-widgets/ipywidgets#1812]
#710 
> Proposal: A base WidgetStyle class which is a widget like Layout, specialized for each widget type exposing higher level abstractions than css. For the SliderStyle object:
> 
> handle color
> slider color
> readout color
> we could limit this to colors at first...

Does not seem to work yet (ipywidgets.__version__ = 7.0.0). I can only set the handle color.
As I am working with a dark background style the default black readout color is very annoying...
Or am I doing something wrong:

```
layout = {'width':'90%', 'height': '80px', 'border': 'solid', 'fontcolor':'red'}
style = {'handle_color': 'red', 'readout_color': 'red', 'slider_color': 'red'}
slides = widgets.interactive(lambda m, f: run(axes, lines, q, p, E, m, twopi*f, dt),
                            f=FloatSlider(min=1, max=100, step=1, continuous_update=False, layout=layout, style=style),
                            m=FloatSlider(min=1, max=100, step=1, continuous_update=False, layout=layout, style=style))
```

**Comment by jasongrout** [comment]
Handle color and description width is the only thing implemented right now for the slider. We thought we'd start conservative.

The description labels and all of the other text probably gives you issues too, right? If you have a dark background, it may be better to change the text color across all of ipywidgets (as part of a theme change), rather than just on a single widget.

**Comment by kramerfelix** [comment]
The description labels are already white. Only the readout labels are black. What do you mean by changing  the text color across all of ipywidgets? Why do ipywidgets not respect my global ipython theme textcolor?

**Comment by jasongrout** [comment]
I'm not familiar with a theming system for ipython notebook. How did you set a "global ipython theme textcolor"?

**Comment by jasongrout** [comment]
(There is official support for themes in JupyterLab, which ipywidgets should respect, but as far as I know, there is no official support for themes in the classic notebook.)

**Comment by kramerfelix** [comment]
Sorry, I was not clear. I am using [jupyterthemes](https://github.com/dunovank/jupyter-themes) with monokai. As mentioned while the description labels obviously respect the themes the readout labels do not.

```python
import jupyter
import jupyterthemes
print(jupyter.__version__)
print(jupyterthemes.__version__)
> 1.0.0
> 0.17.8
```

**Comment by jasongrout** [comment]
Ah, I don't know anything about jupyterthemes. I think the description labels respecting the theme colors may be a happy accident. Can you go into the Chrome debugger and determine what extra css is being applied to the description labels that is not being applied to the readout labels?

**Comment by kramerfelix** [comment]
The description label is getting its color from custom.css line 1802:
```css
div.widget-label {
 text-align: -webkit-auto !important;
 margin-left: 15px !important;
 max-width: 240px !important;
 min-width: 100px !important;
 vertical-align: text-top !important;
 color: #cccccc !important;
 font-size: 14px;
}
```

both are ignoring from custom.css:
```css
div#notebook {
 font-family: sans-serif;
 font-size: 13pt;
 line-height: 170%;
 color: #f8f8f0;
 -webkit-font-smoothing: antialiased !important;
}
body,
div.body {
 font-family: sans-serif;
 font-size: 13pt;
 color: #f8f8f0;
 background-color: #1e1e1e;
 background: #1e1e1e;
 -webkit-font-smoothing: antialiased !important;
}
```
