### ISSUE TITLE
Empty/removed widgets have padding and border

### ISSUE THREAD

**Issue by flying-sheep** [jupyter-widgets/ipywidgets#2074]
`tqdm_notebook(leave=False)` leaves HTML like

```html
<div class="p-Widget p-Panel jp-OutputArea-child">
    <div class="p-Widget jp-OutputPrompt jp-OutputArea-prompt"></div>
    <div class="p-Widget p-Panel p-mod-hidden jp-OutputArea-output"></div>
</div>
```

And while the latter child div ishidden, the former retains space. Would it be possible to add CSS like:

```css
.jp-OutputArea-child > .p-Widget.jp-OutputPrompt.jp-OutputArea-prompt {
    --jp-border-width: 0;
    --jp-code-padding: 0;
}
```
