### ISSUE TITLE
Ability to set border edges independently

### ISSUE THREAD

**Issue by pbugnion** [jupyter-widgets/ipywidgets#920]
If I'm not mistaken, `widget.layout.border` gets translated into adding the CSS `border` property. This property is short-hand for three separate border properties: `border-width`, `border-style`, and `border-color`. By forcing someone to use the shorthand `border` property, rather than the individual properties, there is no way to set different border types for the different border edges. There is no way (AFAICT), for instance, to build the equivalent of a CSS body like:

```css
#mywidget {
  border-style: none none solid none; /* I just want a border at the bottom of my widget */
  border-width: 2px;
  border-color: black;
}
```

My use case is that I'm trying to build a table of widgets. Each row is an `HBox` of several widgets. It would be useful to specify that each row should have a bottom border.

I understand that I can obviously do this with a  custom widget. Nevertheless, this seems like a fairly common use case. We could add three additional unicode traitlets to the `Layout` widget: `border_style`, `border_width` and `border_color`. We could also raise an exception if the user specifies both these and the shorthand `border`.

I'm very happy to submit a PR if people think this would be a useful addition.
